-   id: hlint
    name: hlint
    description: HLint gives suggestions on how to improve your source code.
    entry: hlint
    language: system
    files: '\.l?hs$'
-   id: hlint-ignore-duplication
    name: hlint-ignore-duplication
    description: Runs HLint, but ignores duplications.
    entry: hlint -i 'Reduce duplication'
    language: system
    files: '\.l?hs$'
-   id: hlint-suggestions
    name: hlint-suggestions
    description: HLint gives suggestions on how to improve your source code, but still returns zero exti code.
    entry: hlint --no-exit-code 
    language: system
    files: '\.l?hs$'
-   id: hlint-suggestions-ignore-duplication
    name: hlint-suggestions-ignore-duplication
    description: HLint gives suggestions on how to improve your source code, but still returns zero exti code while ignoring duplication.
    entry: hlint -i 'Reduce duplication' --no-exit-code 
    language: system
    files: '\.l?hs$'
-   id: stylish-haskell
    name: stylish-haskell
    description: Haskell code prettifier.
    entry: stylish-haskell --inplace
    language: system
    files: '\.l?hs$'
